# $OpenBSD$

COMMENT = 		visual toolkit library for 3D rendering
CATEGORIES = 		math devel
HOMEPAGE = 		http://www.vtk.org/
VERSION = 		8.2.0
DISTNAME = 		VTK-${VERSION}
PKGNAME = 		${DISTNAME:L}
MAINTAINER =		Charlie Burnett <burne251@umn.edu>

LIBVER = 		0.0

SHARED_LIBS +=		vtkChartsCore 				${LIBVER}
SHARED_LIBS +=		vtkCommonColor 				${LIBVER}
SHARED_LIBS +=		vtkCommonComputationalGeometry 		${LIBVER}
SHARED_LIBS +=		vtkCommonCore 				${LIBVER}
SHARED_LIBS +=		vtkCommonDataModel 			${LIBVER}
SHARED_LIBS +=		vtkCommonExecutionModel 		${LIBVER}
SHARED_LIBS +=		vtkCommonMath 				${LIBVER}
SHARED_LIBS +=		vtkCommonMisc 				${LIBVER}
SHARED_LIBS +=		vtkCommonSystem 			${LIBVER}
SHARED_LIBS +=		vtkCommonTransforms 			${LIBVER}
SHARED_LIBS +=		vtkDICOMParser 				${LIBVER}
SHARED_LIBS +=		vtkDomainsChemistry 			${LIBVER}
SHARED_LIBS +=		vtkDomainsChemistryOpenGL2 		${LIBVER}
SHARED_LIBS +=		vtkFiltersAMR 				${LIBVER}
SHARED_LIBS +=		vtkFiltersCore 				${LIBVER}
SHARED_LIBS +=		vtkFiltersExtraction 			${LIBVER}
SHARED_LIBS +=		vtkFiltersFlowPaths 			${LIBVER}
SHARED_LIBS +=		vtkFiltersGeneral 			${LIBVER}
SHARED_LIBS +=		vtkFiltersGeneric 			${LIBVER}
SHARED_LIBS +=		vtkFiltersGeometry 			${LIBVER}
SHARED_LIBS +=		vtkFiltersHybrid 			${LIBVER}
SHARED_LIBS +=		vtkFiltersHyperTree 			${LIBVER}
SHARED_LIBS +=		vtkFiltersImaging 			${LIBVER}
SHARED_LIBS +=		vtkFiltersModeling 			${LIBVER}
SHARED_LIBS +=		vtkFiltersParallel 			${LIBVER}
SHARED_LIBS +=		vtkFiltersParallelImaging 		${LIBVER}
SHARED_LIBS +=		vtkFiltersPoints 			${LIBVER}
SHARED_LIBS +=		vtkFiltersProgrammable 			${LIBVER}
SHARED_LIBS +=		vtkFiltersSMP 				${LIBVER}
SHARED_LIBS +=		vtkFiltersSelection 			${LIBVER}
SHARED_LIBS +=		vtkFiltersSources 			${LIBVER}
SHARED_LIBS +=		vtkFiltersStatistics 			${LIBVER}
SHARED_LIBS +=		vtkFiltersTexture 			${LIBVER}
SHARED_LIBS +=		vtkFiltersTopology 			${LIBVER}
SHARED_LIBS +=		vtkFiltersVerdict 			${LIBVER}
SHARED_LIBS +=		vtkGeovisCore 				${LIBVER}
SHARED_LIBS +=		vtkIOAMR 				${LIBVER}
SHARED_LIBS +=		vtkIOAsynchronous 			${LIBVER}
SHARED_LIBS +=		vtkIOCityGML 				${LIBVER}
SHARED_LIBS +=		vtkIOCore 				${LIBVER}
SHARED_LIBS +=		vtkIOEnSight 				${LIBVER}
SHARED_LIBS +=		vtkIOExodus 				${LIBVER}
SHARED_LIBS +=		vtkIOExport 				${LIBVER}
SHARED_LIBS +=		vtkIOExportOpenGL2 			${LIBVER}
SHARED_LIBS +=		vtkIOExportPDF 				${LIBVER}
SHARED_LIBS +=		vtkIOGeometry 				${LIBVER}
SHARED_LIBS +=		vtkIOImage 				${LIBVER}
SHARED_LIBS +=		vtkIOImport 				${LIBVER}
SHARED_LIBS +=		vtkIOInfovis 				${LIBVER}
SHARED_LIBS +=		vtkIOLSDyna 				${LIBVER}
SHARED_LIBS +=		vtkIOLegacy 				${LIBVER}
SHARED_LIBS +=		vtkIOMINC 				${LIBVER}
SHARED_LIBS +=		vtkIOMovie 				${LIBVER}
SHARED_LIBS +=		vtkIONetCDF 				${LIBVER}
SHARED_LIBS +=		vtkIOPLY 				${LIBVER}
SHARED_LIBS +=		vtkIOParallel 				${LIBVER}
SHARED_LIBS +=		vtkIOParallelXML 			${LIBVER}
SHARED_LIBS +=		vtkIOSQL 				${LIBVER}
SHARED_LIBS +=		vtkIOSegY 				${LIBVER}
SHARED_LIBS +=		vtkIOTecplotTable 			${LIBVER}
SHARED_LIBS +=		vtkIOVeraOut 				${LIBVER}
SHARED_LIBS +=		vtkIOVideo 				${LIBVER}
SHARED_LIBS +=		vtkIOXML 				${LIBVER}
SHARED_LIBS +=		vtkIOXMLParser 				${LIBVER}
SHARED_LIBS +=		vtkImagingColor 			${LIBVER}
SHARED_LIBS +=		vtkImagingCore 				${LIBVER}
SHARED_LIBS +=		vtkImagingFourier 			${LIBVER}
SHARED_LIBS +=		vtkImagingGeneral 			${LIBVER}
SHARED_LIBS +=		vtkImagingHybrid 			${LIBVER}
SHARED_LIBS +=		vtkImagingMath 				${LIBVER}
SHARED_LIBS +=		vtkImagingMorphological 		${LIBVER}
SHARED_LIBS +=		vtkImagingSources 			${LIBVER}
SHARED_LIBS +=		vtkImagingStatistics 			${LIBVER}
SHARED_LIBS +=		vtkImagingStencil 			${LIBVER}
SHARED_LIBS +=		vtkInfovisCore 				${LIBVER}
SHARED_LIBS +=		vtkInfovisLayout 			${LIBVER}
SHARED_LIBS +=		vtkInteractionImage 			${LIBVER}
SHARED_LIBS +=		vtkInteractionStyle 			${LIBVER}
SHARED_LIBS +=		vtkInteractionWidgets 			${LIBVER}
SHARED_LIBS +=		vtkNetCDF 				${LIBVER}
SHARED_LIBS +=		vtkParallelCore 			${LIBVER}
SHARED_LIBS +=		vtkRenderingAnnotation 			${LIBVER}
SHARED_LIBS +=		vtkRenderingContext2D 			${LIBVER}
SHARED_LIBS +=		vtkRenderingContextOpenGL2 		${LIBVER}
SHARED_LIBS +=		vtkRenderingCore 			${LIBVER}
SHARED_LIBS +=		vtkRenderingFreeType 			${LIBVER}
SHARED_LIBS +=		vtkRenderingGL2PSOpenGL2 		${LIBVER}
SHARED_LIBS +=		vtkRenderingImage 			${LIBVER}
SHARED_LIBS +=		vtkRenderingLOD 			${LIBVER}
SHARED_LIBS +=		vtkRenderingLabel 			${LIBVER}
SHARED_LIBS +=		vtkRenderingOpenGL2 			${LIBVER}
SHARED_LIBS +=		vtkRenderingVolume 			${LIBVER}
SHARED_LIBS +=		vtkRenderingVolumeOpenGL2 		${LIBVER}
SHARED_LIBS +=		vtkViewsContext2D 			${LIBVER}
SHARED_LIBS +=		vtkViewsCore 				${LIBVER}
SHARED_LIBS +=		vtkViewsInfovis 			${LIBVER}
SHARED_LIBS +=		vtkdoubleconversion 			${LIBVER}
SHARED_LIBS +=		vtkexodusII 				${LIBVER}
SHARED_LIBS +=		vtkexpat 				${LIBVER}
SHARED_LIBS +=		vtkfreetype 				${LIBVER}
SHARED_LIBS +=		vtkgl2ps 				${LIBVER}
SHARED_LIBS +=		vtkglew 				${LIBVER}
SHARED_LIBS +=		vtkhdf5 				${LIBVER}
SHARED_LIBS +=		vtkhdf5_hl 				${LIBVER}
SHARED_LIBS +=		vtkjpeg 				${LIBVER}
SHARED_LIBS +=		vtkjsoncpp 				${LIBVER}
SHARED_LIBS +=		vtklibharu 				${LIBVER}
SHARED_LIBS +=		vtklibxml2 				${LIBVER}
SHARED_LIBS +=		vtklz4 					${LIBVER}
SHARED_LIBS +=		vtklzma 				${LIBVER}
SHARED_LIBS +=		vtkmetaio 				${LIBVER}
SHARED_LIBS +=		vtkogg 					${LIBVER}
SHARED_LIBS +=		vtkpng 					${LIBVER}
SHARED_LIBS +=		vtkproj 				${LIBVER}
SHARED_LIBS +=		vtkpugixml 				${LIBVER}
SHARED_LIBS +=		vtksqlite 				${LIBVER}
SHARED_LIBS +=		vtksys 					${LIBVER}
SHARED_LIBS +=		vtktheora 				${LIBVER}
SHARED_LIBS +=		vtktiff 				${LIBVER}
SHARED_LIBS +=		vtkverdict 				${LIBVER}
SHARED_LIBS +=		vtkzlib 				${LIBVER}

# BSD 3-clause

PERMIT_PACKAGE = 	Yes

MASTER_SITES = 		http://www.vtk.org/files/release/8.2/

COMPILER =		base-clang ports-gcc

MODULES +=		devel/cmake

WANTLIB +=		${COMPILER_LIBCXX}

WANTLIB += 		GL GLU ICE SM X11 Xext Xt m pthread freetype




.include <bsd.port.mk>
